### ISSUE TITLE
How to generate man pages for each entry point ?

### ISSUE THREAD

**Issue by gtristan** [click-contrib/click-man#10]
Seems that when running:

```
python3 setup.py --command-packages=click_man.commands man_pages
```

I dont see how I can tell it to generate man pages for each of the entry points defined in `setup.py`

**Comment by timofurrer** [comment]
Unfortunately, you can't at the moment. It will just generate man pages for the first entry point in `setup()`. 

I don't have time right now to implement that option but I'd be happy to merge patches.
Or you'll just wait a few more days.
