### ISSUE TITLE
use click 7.0 Generate man pages report "AttributeError"

### ISSUE THREAD

**Issue by uighurbabbage** [click-contrib/click-man#21]
# when I use click 7.0 and try to Generate man pages get the error (change 6.7 no this problem):
 1. error info ：
![image](https://user-images.githubusercontent.com/9205255/46129020-f608ec00-c267-11e8-92d5-e652c0640961.png)

 2. mac info:
![image](https://user-images.githubusercontent.com/9205255/46128939-bd691280-c267-11e8-8eef-9bfed83e8432.png)

**Comment by stephenfin** [comment]
This seems to be happening because `Command.short_help` is unset. I'm guessing this is a bug in Click because I wasn't able to find anything in the [release notes](http://click.palletsprojects.com/en/7.x/changelog/) about this.
