### ISSUE TITLE
Add redirect information for subcommands

### ISSUE THREAD

**Issue by BrunnerLivio** [click-contrib/click-man#3]
Let's assume you have the command `my-cmd` with the subcommand `run`. 

When you type `man my-cmd` it shows `run` as a subcommand, how it is supposed to be, but no information that you're able to type `man my-cmd run` to get further information about the subcommand. This can be confusing for some users.

Docker solves this issue by writing this line under every subcommand: 
`See docker-push(1) for full documentation on the push command.`

Maybe something similar would be a nice feature?

**Comment by timofurrer** [comment]
Fix included in **0.2.1**
