### ISSUE TITLE
Description on PyPI isn't formatted correctly

### ISSUE THREAD

**Issue by cs-shadow** [click-contrib/click-man#30]
This is a relatively minor issue but the formatting on https://pypi.org/project/click-man seems broken - the markdown is rendered literally for some reason.

**Comment by ferdnyc** [comment]
This appears to be fixed now — at least, everything looks fine to me when I visit https://pypi.org/project/click-man

**Comment by cs-shadow** [comment]
You are right, it seems alright now.

Let's close this. Thanks!
