### ISSUE TITLE
PyPI release 0.4.2

### ISSUE THREAD

**Issue by lachmanfrantisek** [click-contrib/click-man#65]
Hello!

I just took the maintenance of this package in Fedora (let me know if you need anything..;) and it looks like we still don't have `0.4.2` because we rely on sources from PyPI. Could someone (probably @timofurrer)  release it there?

(In our projects, we use [this](https://github.com/packit/packit/blob/main/.github/workflows/pypi-publish.yml) GitHub action to do it automatically -- I can send a PR if you want.)

Thanks in advance!
František

**Comment by bostrt** [comment]
@lachmanfrantisek I was looking for the 0.4.2 version of this in Fedora. Do you know why its not available yet?

**Comment by captn3m0** [comment]
Mentioned above - https://pypi.org/project/click-man/#history doesn't have 0.4.2, which is what Fedora tracks.

**Comment by bostrt** [comment]
I see, I assumed there was a Pypi release already since there's a tag and GitHub release for 0.4.2. My mistake!

**Comment by stephenfin** [comment]
This is resolved now. 0.5.0 is also out.
