### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by timofurrer** [click-contrib/click-man#68]
I want to add @stephenfin as a new Maintainer.

He's already maintaining other projects in the org, like sphinx-click.

**Comment by timofurrer** [comment]
@davidism I'm not sure who to ping but you are probably someone with proper permissions :)

I'm looking for someone to add @stephenfin as another Maintainer for this project. Can you assist?

**Comment by davidism** [comment]
I've added them to this repo. You'll need to add them to PyPI, and while you're at it can you add me (davidism) as well? I need "owner" not "maintain" on PyPI so I can start moving to pallets-eco and allow more maintainers to manage this in the future.

**Comment by stephenfin** [comment]
@davidism Re-opening as I need the `admin` role to be able to add secrets (for CI-generated releases)

**Comment by davidism** [comment]
I'm finishing up writing a guide on the pallets-eco publishing process today, which will tell you how to kick off a build and release using this workflow. You can chat with me and other maintainers in the `#pallets-eco` channel on our Discord: https://discord.gg/pallets.
